In [3]:
import torch

In [4]:
print(torch.cuda.is_available())
print(torch.__version__)

True
1.6.0


In [9]:
x= torch.rand(5,3)

In [10]:
x

tensor([[0.7275, 0.5278, 0.1355],
        [0.3662, 0.8823, 0.3634],
        [0.8424, 0.1075, 0.5404],
        [0.3551, 0.3529, 0.0250],
        [0.1633, 0.1089, 0.5472]])

In [11]:
y= torch.zeros(5,3,dtype=torch.double)

In [12]:
y

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [16]:
x[:,0]#先行再列

tensor([0.7275, 0.3662, 0.8424, 0.3551, 0.1633])