In [1]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.5.1+cpu


In [3]:
# 定义矩阵
x = torch.empty(2, 2)
print(x)

tensor([[5.8641e-19, 4.5915e-41],
        [5.8641e-19, 4.5915e-41]])


In [5]:
# 定义随机初始化矩阵
x = torch.randn(2, 2)
print(x)

tensor([[-0.7061,  0.6910],
        [ 0.0308,  0.1461]])


In [6]:
# 定义初始化为零
x = torch.zeros(3, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# 定义数据为tensor
x = torch.tensor([5.1, 2., 3., 1.])
print(x)

tensor([5.1000, 2.0000, 3.0000, 1.0000])


In [8]:
# 操作
a = torch.tensor([1.,2.,3.,4.,5.,6.,7.,8.])
b = torch.tensor([11.,12.,13.,14.,15.,16.,17.,18.])
c = a.add(b)
print(c)

tensor([12., 14., 16., 18., 20., 22., 24., 26.])


In [9]:
# 维度变换 2x4
a = a.view(-1, 4)
b = b.view(-1, 4)
c = torch.add(a, b)
print(c, a.size(), b.size())

tensor([[12., 14., 16., 18.],
        [20., 22., 24., 26.]]) torch.Size([2, 4]) torch.Size([2, 4])


In [10]:
# torch to numpy and visa
na = a.numpy()
nb = b.numpy()
print("\na =",na,"\nb =", nb)


a = [[1. 2. 3. 4.]
 [5. 6. 7. 8.]] 
b = [[11. 12. 13. 14.]
 [15. 16. 17. 18.]]


In [11]:
# 操作
d = np.array([21.,22.,23.,24.,25.,26.,27.,28.], dtype=np.float32)
print(d.reshape(2, 4))
d = torch.from_numpy(d.reshape(2, 4))
sum = torch.sub(c, d)
print(sum, "\n sum = ", sum.size())

[[21. 22. 23. 24.]
 [25. 26. 27. 28.]]
tensor([[-9., -8., -7., -6.],
        [-5., -4., -3., -2.]]) 
 sum =  torch.Size([2, 4])


In [14]:
# using CUDA
if torch.cuda.is_available():
    result = d.cuda() + c.cuda()
    print("\n result = ", result)
else:
    print(1)

1


In [15]:
# 自动梯度
#requires_grad需要计算梯度；
x = torch.randn(1, 5, requires_grad=True)
y = torch.randn(5, 3, requires_grad=True)
z = torch.randn(3, 1, requires_grad=True)
print("\nx=",x, "\ny=",y, "\nz=",z)
xy = torch.matmul(x, y)
xyz = torch.matmul(xy, z)
xyz.backward()
print(x.grad, y.grad, z.grad)


x= tensor([[-1.3432,  0.5084, -1.4120, -2.0212, -1.0864]], requires_grad=True) 
y= tensor([[ 1.4878,  1.7829, -1.6050],
        [ 1.0427,  0.2135,  1.7242],
        [-1.4492, -1.0604,  0.5614],
        [-0.9793, -0.6624, -2.6776],
        [ 0.7742, -0.2585, -0.1218]], requires_grad=True) 
z= tensor([[-0.4246],
        [ 0.3049],
        [ 0.3086]], requires_grad=True)
tensor([[-0.5834,  0.1546,  0.4652, -0.6126, -0.4451]]) tensor([[ 0.5703, -0.4096, -0.4145],
        [-0.2159,  0.1550,  0.1569],
        [ 0.5995, -0.4306, -0.4358],
        [ 0.8582, -0.6163, -0.6238],
        [ 0.4613, -0.3313, -0.3353]]) tensor([[1.7162],
        [0.8308],
        [7.7839]])


In [6]:
a=torch.ones(3,1,2)
b=torch.ones(2,1)
c=torch.ones(2,3)

In [4]:
 (a+b).size()

torch.Size([3, 2, 2])

In [7]:
(a+c).size()

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [8]:
 a=torch.randn(2,2)

In [9]:
b=a

In [11]:
a

tensor([[ 1.5183,  1.2175],
        [-0.7060,  0.1683]])

In [12]:
b

tensor([[ 1.5183,  1.2175],
        [-0.7060,  0.1683]])

In [13]:
c=a.view(4)

In [14]:
c

tensor([ 1.5183,  1.2175, -0.7060,  0.1683])

In [15]:
b[0,0]=0

In [16]:
b

tensor([[ 0.0000,  1.2175],
        [-0.7060,  0.1683]])

In [17]:
c[3]=4

In [18]:
c

tensor([ 0.0000,  1.2175, -0.7060,  4.0000])

In [19]:
a

tensor([[ 0.0000,  1.2175],
        [-0.7060,  4.0000]])

In [20]:
b

tensor([[ 0.0000,  1.2175],
        [-0.7060,  4.0000]])

In [21]:
a=torch.Tensor([[1,2],[3,4]])

In [22]:
a

tensor([[1., 2.],
        [3., 4.]])

In [23]:
b=a.add_(a)

In [24]:
b

tensor([[2., 4.],
        [6., 8.]])

In [25]:
a

tensor([[2., 4.],
        [6., 8.]])

In [26]:
c=a.resize_(4)

In [27]:
a

tensor([2., 4., 6., 8.])

In [28]:
c

tensor([2., 4., 6., 8.])

In [29]:
c=a.resize_(3)

In [30]:
c

tensor([2., 4., 6.])

In [31]:
a

tensor([2., 4., 6.])

In [32]:
c=a.resize_(2)

In [33]:
c

tensor([2., 4.])

In [34]:
a

tensor([2., 4.])

In [35]:
c=a.resize_(4)

In [36]:
c

tensor([2., 4., 6., 8.])

In [37]:
a

tensor([2., 4., 6., 8.])

In [38]:
a=torch.randn(1,2)

In [39]:
a

tensor([[-0.4245,  0.9800]])

In [40]:
b=a.numpy()

In [41]:
b

array([[-0.42452344,  0.9799566 ]], dtype=float32)

In [42]:
a

tensor([[-0.4245,  0.9800]])

In [43]:
c=torch.from_numpy(b)

In [44]:
c

tensor([[-0.4245,  0.9800]])

In [45]:
c==a

tensor([[True, True]])

In [46]:
d=a.tolist()

In [47]:
d

[[-0.4245234429836273, 0.9799566268920898]]

In [48]:
 a = torch.randn(2,2, requires_grad=True)

In [49]:
a

tensor([[-0.6521, -0.3534],
        [ 0.4480, -0.9007]], requires_grad=True)

In [50]:
x = torch.randn(1)

In [51]:
x

tensor([-0.8102])

In [52]:
 w = torch.ones(1, requires_grad=True)

In [53]:
w

tensor([1.], requires_grad=True)

In [54]:
b = torch.ones(1, requires_grad=True)

In [55]:
b

tensor([1.], requires_grad=True)

In [56]:
x.is_leaf, w.is_leaf, b.is_leaf

(True, True, True)

In [57]:
x.requires_grad, w.requires_grad, b.requires_grad

(False, True, True)

In [58]:
y=w*x

In [59]:
y

tensor([-0.8102], grad_fn=<MulBackward0>)

In [60]:
z=y+b

In [61]:
z

tensor([0.1898], grad_fn=<AddBackward0>)

In [62]:
y.is_leaf, z.is_leaf

(False, False)

In [63]:
y.requires_grad, z.requires_grad

(True, True)

In [64]:
y.grad_fn

In [65]:
z.grad_fn

In [66]:
 z.backward(retain_graph=True)

In [67]:
w.grad

tensor([-0.8102])

In [68]:
 b.grad

tensor([1.])

In [74]:
score = torch.randn(1,4)

In [75]:
score

tensor([[ 0.2264,  0.9814, -0.2997,  0.4821]])

In [76]:
 import torch.nn.functional as F

In [81]:
 F.softmax(score, 1)

tensor([[0.1996, 0.4247, 0.1179, 0.2578]])

In [82]:
from torch import nn

In [83]:
dropout = nn.Dropout(0.5, inplace=False)

In [88]:
input = torch.randn(2, 2, 7, 7)

In [89]:
input

tensor([[[[-0.7999,  0.4571, -0.7731, -0.9421,  1.5432,  1.7292, -1.1794],
          [-1.8036, -0.2742, -0.4250,  0.8906, -0.2832, -1.4465,  0.7268],
          [-0.0514,  0.7739, -0.5517, -1.7854, -0.3382, -0.5423,  1.2011],
          [-0.8241, -0.7735, -0.9301, -1.3836,  1.3418,  0.4812,  0.6115],
          [-0.6965,  0.8784, -1.3378, -1.3756, -1.3002, -0.7261,  2.4049],
          [-1.0243, -0.1076, -0.9359,  1.4002, -0.8578,  0.4523, -0.5916],
          [ 1.4841, -0.1707, -0.6925, -0.0757, -0.5128,  1.3285,  0.1598]],

         [[-2.1818,  0.4381,  0.4846,  0.2136,  0.4540, -2.0582, -0.5905],
          [-0.8623, -0.4892, -0.4721, -0.3235,  0.0489, -0.8850,  0.0082],
          [-0.4857,  0.6328, -0.2539,  0.6846,  0.4658, -2.8459,  2.3162],
          [ 1.2830, -0.1256,  1.6599, -2.2900, -1.4373, -0.1968,  1.0553],
          [ 0.5210,  0.2188, -0.5191,  1.2875,  0.0232,  0.1458, -1.5699],
          [ 0.2753,  0.7542,  0.6786,  0.1142, -1.2870,  2.5145,  1.3163],
          [-0.8563,  0.

In [90]:
output = dropout(input)

In [91]:
output

tensor([[[[-0.0000,  0.9142, -1.5462, -1.8843,  3.0863,  0.0000, -2.3588],
          [-0.0000, -0.5484, -0.8500,  1.7812, -0.5664, -0.0000,  1.4535],
          [-0.0000,  0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.0000],
          [-0.0000, -1.5470, -1.8602, -0.0000,  2.6837,  0.0000,  1.2229],
          [-1.3930,  1.7568, -2.6756, -0.0000, -0.0000, -0.0000,  0.0000],
          [-0.0000, -0.0000, -0.0000,  0.0000, -0.0000,  0.0000, -1.1831],
          [ 0.0000, -0.0000, -0.0000, -0.1513, -1.0256,  0.0000,  0.3196]],

         [[-0.0000,  0.8762,  0.0000,  0.0000,  0.9079, -4.1163, -0.0000],
          [-0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -1.7700,  0.0000],
          [-0.9715,  0.0000, -0.0000,  0.0000,  0.9317, -5.6919,  4.6324],
          [ 2.5660, -0.2512,  3.3199, -0.0000, -0.0000, -0.3937,  2.1106],
          [ 1.0420,  0.4377, -0.0000,  2.5750,  0.0464,  0.2916, -3.1398],
          [ 0.5506,  1.5084,  0.0000,  0.0000, -2.5739,  0.0000,  0.0000],
          [-1.7125,  0.