In [1]:
import torch
print(torch.cuda.is_available())
print(torch.__version__)

True
1.6.0


In [2]:
a = torch.Tensor([[0,1], [2, 3]])

In [3]:
print(a)

tensor([[0., 1.],
        [2., 3.]])


In [4]:
torch.where(a>1, torch.full_like(a, 1), a)

tensor([[0., 1.],
        [1., 1.]])

In [5]:
 b=torch.arange(1,5)

In [6]:
b

tensor([1, 2, 3, 4])

In [7]:
c=b.view(2,2)

In [8]:
c

tensor([[1, 2],
        [3, 4]])

In [9]:
c=b.reshape(2,2)

In [10]:
c

tensor([[1, 2],
        [3, 4]])

In [12]:
c=b.resize(2,2)

D:\Anaconda3\envs\torch\lib\site-packages\torch\tensor.py:358: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [13]:
c

tensor([[1, 2],
        [3, 4]])

In [14]:
c=b.reshape(4,1)

In [15]:
c

tensor([[1],
        [2],
        [3],
        [4]])

In [20]:
c=b.resize_(4,1)

In [21]:
c

tensor([[1],
        [2],
        [3],
        [4]])

In [22]:
 a=torch.randn(2,2,2)

In [23]:
a

tensor([[[ 0.9954, -0.1969],
         [ 0.5217, -0.9601]],

        [[ 0.5963,  0.5115],
         [ 0.8241, -3.3192]]])

In [29]:
a.size()

torch.Size([2, 2, 2])

In [30]:
a.transpose(0,1)

tensor([[[ 0.9954, -0.1969],
         [ 0.5963,  0.5115]],

        [[ 0.5217, -0.9601],
         [ 0.8241, -3.3192]]])

In [34]:
 a.transpose(0,2)

tensor([[[ 0.9954,  0.5963],
         [ 0.5217,  0.8241]],

        [[-0.1969,  0.5115],
         [-0.9601, -3.3192]]])

In [35]:
 a=torch.arange(1,4)

In [36]:
a

tensor([1, 2, 3])

In [56]:
b

tensor([[1],
        [2],
        [3],
        [4]])

In [57]:
b.unsqueeze(0)

tensor([[[1],
         [2],
         [3],
         [4]]])

In [4]:
import numpy as np
a = np.arange(24).reshape(2,3,4)
b = a.swapaxes(0,1)
print(a)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [6]:
import numpy as np
a = np.arange(10).reshape(2,5)
#b =np.flatten()
c = a.reshape(-1)
d = a.ravel()
print(a)
#print(b)
print(c)
print(d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
b =np.flatten()
print(b)

AttributeError: module 'numpy' has no attribute 'flatten'